(() => {
  const {TAMA}=window; TAMA.theme.init(); let products=[], editId=null, activeChat=null, chatTimer=null;
  function ready(){if(TAMA.configError){TAMA.toast(TAMA.configMessage||'Konfigurasi Supabase belum tersedia. Tambahkan SUPABASE_URL dan SUPABASE_ANON_KEY di Vercel.');return false}return true}
  async function isAdmin(){const {data:{user}}=await TAMA.sb.auth.getUser();if(!user)return false;const email=(user.email||'').trim().toLowerCase();if(email==='fyesty8@gmail.com')return true;const {data,error}=await TAMA.sb.from('admins').select('email').eq('email',user.email).maybeSingle();return !error&&!!data}
  async function boot(){if(!ready())return;const ok=await isAdmin();const {data:{session}}=await TAMA.sb.auth.getSession();if(ok&&session){showAdmin();}else{TAMA.q('#loginView').classList.remove('hidden');TAMA.q('#adminView').classList.add('hidden')}}
  function showAdmin(){TAMA.q('#loginView').classList.add('hidden');TAMA.q('#adminView').classList.remove('hidden');TAMA.q('#logoutBtn').classList.remove('hidden');loadProducts();loadChats();loadReviews()}
  TAMA.q('#adminLogin').addEventListener('click',async()=>{if(!ready())return;const email=TAMA.q('#adminEmail').value.trim(),password=TAMA.q('#adminPassword').value;if(!email||!password)return TAMA.toast('Email dan password wajib diisi.');const {error}=await TAMA.sb.auth.signInWithPassword({email,password});if(error)return TAMA.toast(error.message);if(!(await isAdmin())){await TAMA.sb.auth.signOut();return TAMA.toast('Akun ini bukan admin. Jalankan SQL setup admin terlebih dahulu.')}showAdmin()});
  TAMA.q('#logoutBtn').addEventListener('click',async()=>{await TAMA.sb.auth.signOut();location.reload()});
  async function upload(file,prefix){const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${prefix}-${crypto.randomUUID()}.${ext}`;const storage=TAMA.sb.storage.from('product-images');const {error}=await storage.upload(path,file,{upsert:false});if(error){if(/bucket.*not found/i.test(error.message||'')){throw new Error('Bucket product-images belum tersedia. Jalankan supabase.sql versi terbaru di Supabase SQL Editor.')}throw error}const {data}=storage.getPublicUrl(path);return {path,url:data.publicUrl}}
  function resetForm(){editId=null;TAMA.q('#productForm').reset();TAMA.q('#formTitle').textContent='Tambah produk';TAMA.q('#cancelEdit').classList.add('hidden')}
  TAMA.q('#cancelEdit').addEventListener('click',resetForm);
  TAMA.q('#productForm').addEventListener('submit',async e=>{e.preventDefault();if(!ready())return;try{const title=TAMA.q('#productTitle').value.trim(),description=TAMA.q('#productDescription').value.trim(),price=Number(TAMA.q('#productPrice').value);let thumbUrl=null,thumbPath=null;if(TAMA.q('#thumbnailFile').files[0]){const up=await upload(TAMA.q('#thumbnailFile').files[0],'thumb');thumbPath=up.path;thumbUrl=up.url}
      let product;
      if(editId){const update={title,description,price};if(thumbUrl){update.thumbnail_url=thumbUrl;update.thumbnail_path=thumbPath}const {data,error}=await TAMA.sb.from('products').update(update).eq('id',editId).select().single();if(error)throw error;product=data}
      else{if(!thumbUrl)return TAMA.toast('Thumbnail wajib dipilih.');const {data,error}=await TAMA.sb.from('products').insert({title,description,price,thumbnail_url:thumbUrl,thumbnail_path:thumbPath,image_url:thumbUrl}).select().single();if(error)throw error;product=data}
      if(TAMA.q('#galleryFiles').files.length){const files=[...TAMA.q('#galleryFiles').files];for(let i=0;i<files.length;i++){const up=await upload(files[i],'gallery');const {error}=await TAMA.sb.from('product_images').insert({product_id:product.id,image_url:up.url,image_path:up.path,sort_order:i});if(error)throw error}}
      TAMA.toast(editId?'Produk diperbarui.':'Produk ditambahkan.');resetForm();loadProducts();
    }catch(err){TAMA.toast(err.message||'Gagal menyimpan produk.')}});
  async function loadProducts(){const {data,error}=await TAMA.sb.from('products').select('*').order('created_at',{ascending:false});if(error)return TAMA.toast(error.message);products=data||[];renderAdminProducts()}
  function renderAdminProducts(){const q=(TAMA.q('#adminSearch').value||'').toLowerCase();const list=products.filter(p=>(p.title||'').toLowerCase().includes(q)||(p.description||'').toLowerCase().includes(q));TAMA.q('#productCount').textContent=`${list.length} produk`;TAMA.q('#adminProducts').innerHTML=list.map(p=>`<div class="admin-product"><img src="${TAMA.escape(p.thumbnail_url||'')}" alt="${TAMA.escape(p.title)}" data-zoom-src="${TAMA.escape(p.thumbnail_url||'')}"><div><h3>${TAMA.escape(p.title)}</h3><p>${TAMA.rupiah(p.price)}</p><span class="hint">Akun siap dipasarkan</span></div><div class="admin-product-actions"><button class="mini-btn" data-edit="${p.id}">Edit</button><button class="mini-btn danger" data-del="${p.id}">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada produk.</div>'}
  TAMA.q('#adminSearch').addEventListener('input',renderAdminProducts);
  TAMA.q('#adminProducts').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]');if(ed)editProduct(ed.dataset.edit);if(del)deleteProduct(del.dataset.del)});
  async function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editId=id;TAMA.q('#formTitle').textContent='Edit produk';TAMA.q('#productId').value=id;TAMA.q('#productTitle').value=p.title;TAMA.q('#productDescription').value=p.description;TAMA.q('#productPrice').value=p.price;TAMA.q('#cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
  async function deleteProduct(id){if(!confirm('Hapus produk ini?'))return;const {error}=await TAMA.sb.from('product_images').delete().eq('product_id',id);if(error)return TAMA.toast(error.message);const p=products.find(x=>x.id===id);const {error:e2}=await TAMA.sb.from('products').delete().eq('id',id);if(e2)return TAMA.toast(e2.message);if(p?.thumbnail_path)await TAMA.sb.storage.from('product-images').remove([p.thumbnail_path]);TAMA.toast('Produk dihapus.');loadProducts()}

  async function loadChats(){const {data,error}=await TAMA.sb.from('chats').select('*').eq('status','open').order('updated_at',{ascending:false});if(error)return;const chats=data||[];TAMA.q('#chatList').innerHTML=chats.length?chats.map(c=>`<button class="chat-list-item ${activeChat?.id===c.id?'active':''}" data-chat="${c.id}"><strong>${TAMA.escape(c.username)}</strong><span>${TAMA.escape(c.category)} · ${c.status==='open'?'Open':'Closed'}</span></button>`).join(''):'<div class="empty">Belum ada chat.</div>'}
  TAMA.q('#refreshChats').addEventListener('click',loadChats);TAMA.q('#chatList').addEventListener('click',e=>{const b=e.target.closest('[data-chat]');if(b)selectChat(b.dataset.chat)});
  async function selectChat(id){const {data,error}=await TAMA.sb.from('chats').select('*').eq('id',id).single();if(error)return TAMA.toast(error.message);activeChat=data;TAMA.q('#adminChatEmpty').classList.add('hidden');TAMA.q('#adminChatActive').classList.remove('hidden');TAMA.q('#adminChatUser').textContent='@'+data.username;TAMA.q('#adminChatCategory').textContent=data.category;TAMA.q('#adminEndChat').disabled=data.status==='closed';TAMA.q('#adminChatInput').disabled=data.status==='closed';TAMA.q('#adminSendChat').disabled=data.status==='closed';await refreshAdminMessages();loadChats()}
  async function refreshAdminMessages(){if(!activeChat)return;const {data,error}=await TAMA.sb.from('chat_messages').select('*').eq('chat_id',activeChat.id).order('created_at');if(error)return;TAMA.q('#adminChatMessages').innerHTML=(data||[]).map(m=>`<div class="msg ${m.sender_type==='user'?'user':'admin'}">${TAMA.escape(m.message)}<small>${new Date(m.created_at).toLocaleString('id-ID')}</small></div>`).join('');const box=TAMA.q('#adminChatMessages');box.scrollTop=box.scrollHeight}
  async function adminSend(){if(!activeChat)return;const input=TAMA.q('#adminChatInput'),text=input.value.trim();if(!text||activeChat.status==='closed')return;const {error}=await TAMA.sb.from('chat_messages').insert({chat_id:activeChat.id,sender_type:'admin',message:text});if(error)return TAMA.toast(error.message);await TAMA.sb.from('chats').update({updated_at:new Date().toISOString()}).eq('id',activeChat.id);input.value='';refreshAdminMessages();loadChats()}
  TAMA.q('#adminSendChat').addEventListener('click',adminSend);TAMA.q('#adminChatInput').addEventListener('keydown',e=>{if(e.key==='Enter')adminSend()});TAMA.q('#adminEndChat').addEventListener('click',async()=>{if(!activeChat)return;const id=activeChat.id;const {error}=await TAMA.sb.from('chats').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',id);if(error)return TAMA.toast(error.message);activeChat=null;TAMA.q('#adminChatActive').classList.add('hidden');TAMA.q('#adminChatEmpty').classList.remove('hidden');await loadChats();TAMA.toast('Chat ditutup dan dihapus dari daftar admin.')});
  chatTimer=setInterval(()=>{if(activeChat)refreshAdminMessages();loadChats()},3000);

  async function loadReviews(){const {data,error}=await TAMA.sb.from('reviews').select('*').order('created_at',{ascending:false});if(error)return;TAMA.q('#adminReviews').innerHTML=(data||[]).map(r=>`<div class="admin-review"><div><strong>${TAMA.escape(r.username)}</strong><div class="review-stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><div class="muted">${TAMA.escape(r.text||r.comment||r.review_text||r.content||r.message||'')}</div></div><div class="review-actions"><button class="mini-btn" data-toggle-review="${r.id}">${r.published?'Sembunyikan':'Tampilkan'}</button><button class="mini-btn danger" data-delete-review="${r.id}">Hapus</button></div></div>`).join('')||'<div class="empty">Belum ada ulasan.</div>'}
  TAMA.q('#refreshReviews').addEventListener('click',loadReviews);TAMA.q('#adminReviews').addEventListener('click',async e=>{const t=e.target.closest('[data-toggle-review]'),d=e.target.closest('[data-delete-review]');if(t){const {data}=await TAMA.sb.from('reviews').select('published').eq('id',t.dataset.toggleReview).single();await TAMA.sb.from('reviews').update({published:!data.published}).eq('id',t.dataset.toggleReview);loadReviews()}if(d){if(!confirm('Hapus ulasan ini?'))return;await TAMA.sb.from('reviews').delete().eq('id',d.dataset.deleteReview);loadReviews()}});
  boot();
})();
